spring.application.name=backend

server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://localhost:5432/sevasahayak
spring.datasource.username=postgres
spring.datasource.password=Kumar@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never